### ISSUE TITLE
Add dynamic OG images

### ISSUE THREAD

**Issue by amirhouieh** [unbody-io/unbody.io#3]
Currently we do not render opengraph-image in any of the pages we have. [NextJS](https://nextjs.org/docs/app/building-your-application/optimizing/metadata#dynamic-image-generation) do support this and in fact Nextra has also added this feature and so we should be able to do so. 

Here is a sample design for the OG. the title is dynamic and the rest of content can be hardcoded for now. 

![Group 12](https://github.com/unbody-io/unbody.io/assets/7159454/8ea58bdd-4198-469a-9eff-821be4eb1ad3)

**Comment by MasuodRj** [comment]
// pages/api/opengraph.js (or any other endpoint)
import { createCanvas, loadImage } from 'canvas';

export default async (req, res) => {
  // Get the dynamic title from your API or request
  const title = req.query.title || 'Default Title';

  // Create a canvas for your image
  const canvas = createCanvas(1200, 630);
  const ctx = canvas.getContext('2d');

  // Load your Open Graph image template
  const template = await loadImage('path/to/og-template.png');
  ctx.drawImage(template, 0, 0);

  // Customize the image with dynamic title
  ctx.font = 'bold 48px Arial';
  ctx.fillStyle = '#fff';
  ctx.fillText(title, 100, 100);

  // Convert the canvas to a PNG image
  const ogImage = canvas.toBuffer('image/png');

  // Set response headers and send the image
  res.setHeader('Content-Type', 'image/png');
  res.setHeader('Content-Length', ogImage.length);
  res.send(ogImage);
};
// pages/blog/[slug].js (or any other page)
import Head from 'next/head';

function BlogPost({ title, content }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta property="og:title" content={title} />
        <meta property="og:image" content={`/api/opengraph?title=${title}`} />
        {/* Add other Open Graph meta tags as needed */}
      </Head>
      {/* Render your page content */}
    </>
  );
}

export default BlogPost;

**Comment by MasuodRj** [comment]
// pages/api/opengraph.js
import { createCanvas, loadImage, registerFont } from 'canvas';

// Register any custom fonts if needed
// registerFont('path/to/custom-font.ttf', { family: 'CustomFont' });

export default async (req, res) => {
  try {
    // Fetch the dynamic title from the request or from your database
    const { title } = req.query;

    // Load a background image
    const bgImage = await loadImage('path/to/background-image.jpg');

    // Create a canvas
    const canvas = createCanvas(1200, 630);
    const ctx = canvas.getContext('2d');

    // Draw the background image
    ctx.drawImage(bgImage, 0, 0, 1200, 630);

    // Customize text styles
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 48px Arial';

    // Draw the dynamic title on the image
    ctx.fillText(title, 100, 100);

    // Export the image as PNG
    res.setHeader('Content-Type', 'image/png');
    canvas.pngStream().pipe(res);
  } catch (error) {
    console.error(error);
    res.status(500).end();
  }
};
// Example page where you want to display the Open Graph image
import Head from 'next/head';

function MyPage() {
  const ogImageUrl = `/api/opengraph?title=My%20Dynamic%20Title`;

  return (
    <div>
      <Head>
        <meta property="og:image" content={ogImageUrl} />
        {/* Add other Open Graph meta tags */}
      </Head>
      {/* Rest of your page content */}
    </div>
  );
}

export default MyPage;

**Comment by MasuodRj** [comment]
//ogImage.js
import html2canvas from 'html2canvas';

export default async function generateOpenGraphImage(title) {
  const ogImageContainer = document.createElement('div');
  ogImageContainer.style.width = '1200px'; //  Open Graph
  ogImageContainer.style.height = '630px'; //  Open Graph
  ogImageContainer.style.backgroundColor = '#0078D4'; // 

  const ogImageTitle = document.createElement('h1');
  ogImageTitle.innerText = title;
  ogImageTitle.style.color = '#FFFFFF'; // 
  ogImageTitle.style.fontSize = '48px'; // 
  ogImageTitle.style.padding = '40px'; // 

  ogImageContainer.appendChild(ogImageTitle);

  //  ogImageContainer 
  const canvas = await html2canvas(ogImageContainer);
  const image = canvas.toDataURL('image/png');

  return image;
}
// در فایل page.mdx
import generateOpenGraphImage from '../path/to/ogImage';

// ...

// 
const dynamicTitle = ' Open Graph';

// Open Graph 
const ogImageUrl = await generateOpenGraphImage(dynamicTitle);

//  Open Graph
<Meta
  title="page title"
  description="Page description"
  image={ogImageUrl}
/>

// 
// ...
