### ISSUE TITLE
Responsive Hero Section

### ISSUE THREAD

**Issue by afragerami** [unbody-io/unbody.io#6]
Our mobile responsive design looks like the photo below:
![image](https://github.com/unbody-io/unbody.io/assets/22498416/f9aeaca6-4e39-405d-9c97-6608ce4d214c)
I suggest making the fonts smaller, so we have the "GET STARTED FOR FREE" button available right away, so the user wont have to scroll

Also it's not showing good on tablet. I suggest reducing the padding button on text, so the button and other things show up
![image](https://github.com/unbody-io/unbody.io/assets/22498416/e68f585c-4e17-4e6e-a960-8e0fa08a5031)

**Comment by amirhouieh** [comment]
This needs to wait as very likely ,the copy and how hero looks is going to be revamped soon.
